WITH LongestDurationProjects AS (
	SELECT 
		ID,
		TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE) AS DURATION,
		RANK() OVER (ORDER BY TIMESTAMPDIFF(MONTH, START_DATE, FINISH_DATE) DESC) AS rnk
	FROM project
)
SELECT 
	ID,
	DURATION AS MONTH_COUNT
FROM LongestDurationProjects
WHERE rnk = 1;